# Dependabot configuration file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
      minor-and-patch:
        applies-to: security-updates
        update-types: [
            "version-update:semver-patch",
            "version-update:semver-minor"
        ]
      support-dependencies:
        applies-to: version-updates
        update-types: [
          "version-update:semver-patch",
          "version-update:semver-minor"
        ]
      ignore:
        - dependency-name: "npm"
          update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ignore:
        - dependency-name: "npm"
          update-types: [ "version-update:semver-major" ]
