const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'src', 'components');

function walk(directory) {
  let results = [];
  const list = fs.readdirSync(directory);
  list.forEach(file => {
    file = path.join(directory, file);
    const stat = fs.statSync(file);
    if (stat && stat.isDirectory()) {
      results = results.concat(walk(file));
    } else {
      if (file.endsWith('.tsx')) {
        results.push(file);
      }
    }
  });
  return results;
}

const files = walk(dir);

files.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let original = content;

  // Backgrounds
  content = content.replace(/bg-neutral-900\/60/g, 'bg-card/60');
  content = content.replace(/bg-neutral-900/g, 'bg-card');
  content = content.replace(/bg-black/g, 'bg-background');
  content = content.replace(/bg-gray-900/g, 'bg-card');
  content = content.replace(/bg-gray-800\/50/g, 'bg-muted/50');
  content = content.replace(/bg-gray-800/g, 'bg-muted');
  
  // Borders
  content = content.replace(/border-neutral-800/g, 'border-border');
  content = content.replace(/border-neutral-700/g, 'border-border');
  content = content.replace(/border-gray-700/g, 'border-border');

  // Text colors
  content = content.replace(/text-neutral-500/g, 'text-muted-foreground');
  content = content.replace(/text-neutral-400/g, 'text-muted-foreground');
  content = content.replace(/text-neutral-300/g, 'text-foreground');
  content = content.replace(/text-gray-400/g, 'text-muted-foreground');
  content = content.replace(/text-gray-300/g, 'text-foreground');
  content = content.replace(/text-gray-200/g, 'text-foreground');
  
  // Hover states
  content = content.replace(/hover:bg-neutral-800/g, 'hover:bg-accent hover:text-accent-foreground');
  content = content.replace(/hover:text-white/g, ''); // Handled by hover:text-accent-foreground
  
  // Modals text-white replacements (most text-white on black backgrounds should be text-foreground)
  content = content.replace(/text-white(?! font-sans)/g, 'text-foreground');
  
  // Re-fix primary badges and buttons that were changed to text-foreground
  content = content.replace(/bg-cyan-600 hover:bg-cyan-700 text-foreground/g, 'bg-cyan-600 hover:bg-cyan-700 text-white');
  content = content.replace(/bg-cyan-500 text-foreground/g, 'bg-cyan-500 text-white');
  content = content.replace(/bg-green-500 text-foreground/g, 'bg-green-500 text-white');
  content = content.replace(/bg-red-600 text-foreground/g, 'bg-red-600 text-white');
  content = content.replace(/bg-orange-600 text-foreground/g, 'bg-orange-600 text-white');
  content = content.replace(/bg-yellow-600 text-foreground/g, 'bg-yellow-600 text-white');
  content = content.replace(/bg-neutral-600 text-foreground/g, 'bg-neutral-600 text-white');
  
  // Also clean up any double spaces generated by hover:text-white removal
  content = content.replace(/  +/g, ' ');
  content = content.replace(/ \}/g, '}');
  content = content.replace(/ "/g, '"');

  if (original !== content) {
    fs.writeFileSync(file, content, 'utf8');
    console.log('Updated', file);
  }
});
